title: Lennart Wittchen (B.Eng.)
logo: /assets/img/image.png
description: Student at University of Duisburg-Essen (Energy and Finance, M.Sc.) - Energy Market Analyst / Commodity Trading / Data Enthusiastic 
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
